Microverse linters project
mwakiogeofrey/LINTERS-PROJECT pull request #1
Opened 2023-03-21 10:16 UTC by mwakiogeofrey

The project is about adding linters in the project and check for errors.

2023-03-21 21:43 UTC, divinecharlotte requested changes
Hi @mwakiogeofrey   ,
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## To Highlight :100:
- No linters errors :heavy_check_mark:
- Descriptive commit messages :heavy_check_mark:
- clean code :heavy_check_mark:
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes :recycle:

_Check the comments under the review._
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 21:43 UTC, divinecharlotte commented on .github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
- [ ] kindly consider setting up your linters correctly so that all of the will be green this will help you meet the below project requirements 
> - Linter should be set up correctly for this repository.
> - Linter result should be green. AKA: Linter should report NO errors.

2023-03-21 21:43 UTC, divinecharlotte commented on README.md
> +</div>
- [ ] kindly consider removing this microverse logo tho its not even being displayed or add yours if you have any 
- [ ] kindly consider customising your readme title to as its related to your project not microverse 

all the above will make your readme personal and professional

2023-03-21 21:43 UTC, divinecharlotte commented on README.md
> +# LINTERS-PROJECT
- [ ] kindly consider removing one title to make your readme more professional

2023-03-21 21:43 UTC, divinecharlotte commented on README.md
> +**[LINTERS PROJECT]** is a...
- [ ] kindly consider removing line to avoid unfinished sentences which are not profesional

2023-03-21 21:43 UTC, divinecharlotte commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] kindly consider adding your  working MIT license link to make a good user experience to the people visiting your project

2023-03-22 18:14 UTC, topeogunleye commented on README.md
> +**[LINTERS PROJECT]** is a...
@mwakiogeofrey, you haven't removed the line yet. please kindly remove it

2023-03-22 18:21 UTC, topeogunleye requested changes
Hi @mwakiogeofrey, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
_Check the comments under the review._
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/52934128/227000789-afcf4755-b251-4b2e-bcd5-15b8ed011e24.png">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

- [ ] Next time, and for future Pull Requests, please kindly add a more descriptive PR title and description as seen in the demo below:
![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 18:21 UTC, topeogunleye commented on README.md
> +    <li><a href="https://reactjs.org/">React.js</a></li>
- [ ] [OPTIONAL] I kindly suggest that you please replace `React.js`, `Express.js`, and `PostgreSQL` with the actual tech stack used in this project which is `HTML`, and `CSS`.

## EXAMPLE

```
<details>
  <summary>Client</summary>
  <ul>
    <li><a href="https://reactjs.org/](https://developer.mozilla.org/en-US/docs/Web/HTML">HTML</a></li>
    <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS">CSS</a></li>
    <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript">JavaScript</a></li>
  </ul>
</details>
```

2023-03-22 19:03 UTC, topeogunleye approved these changes
### Hi @mwakiogeofrey, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 19:04 UTC, merged